apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungry-panda
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: hungry-panda
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  env:
  - name: GREETING_MSG
    value: I'm a hungry Panda!
  - name: GREETING_DESC
    value: I eat bamboo all day
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: "/api-docs"
      owner: cloud-native-applications-team
      system: hungry-pandas
      description: "A set of API endpoints to view k8s data of Hungry-Panda application."
#  serviceClaims:
#  - name: psql
#    ref:
#      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
#      kind: ClassClaim
#      name: psql-1
#  serviceClaims:
#  - name: db
#    ref:
#      # services.apps.tanzu.vmware.com/v1alpha1:ClassClaim:mysql-1
#      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
#      kind: ClassClaim
#      name: psql-1
  source:
    git:
      ref:
        branch: master
      url: https://github.com/GuyBalmas/hungry-panda.git
